#!/bin/bash
#This is creation and calling of shell variable --- defining variables
Class=V-Keys
Batch=13
PROFESSION=AWS/DevOps
echo "Class Name is $Class, Batch number $Batch, We are learning $PROFESSION"
